### ISSUE TITLE
Support for custom database formats

### ISSUE THREAD

**Issue by Phaen** [rseichter/automx2#14]
I use PostfixAdmin to manage the domains and accounts on my mail server, so I need automx2 to be able to query its database. The previous version and alternatives like email-autoconf supported arbitrary database formats by allowing you to provide a query, but this is missing in automx2. Any chance we can get support for something like that, which is far from an edge use cage?

**Comment by rseichter** [comment]
As visible in the source code, automx2 does not use SQL queries directly but instead relies on SQLalchemy as a database abstraction layer, with SQLalchemy generating and executing the necessary commands depending on the configured database backend type. That means if you want to "customise" queries, you need to insert yourself in SQLalchemy's processing. I don't know if that is possible, and as I am currently hospitalised, I am unable to even research the subject.

**Comment by rseichter** [comment]
Addendum: Have you considered populating the automx2 database with content derived from PostfixAdmin's data? That should be easy enough to do.
