### ISSUE TITLE
MS Outlook: which version and OS works for autodiscover?

### ISSUE THREAD

**Issue by HLFH** [rseichter/automx2#15]
Hello!

Could you specify which version of MS Outlook (version and OS) supports the autodiscover protocol with `automx2`?
Or which one did you test and it works?

Does it really support Outlook 2016 (Windows I guess)? https://rseichter.github.io/automx2/#autodiscover
I mean when you log the requests, it does seem they do expect an Exchange ActiveSync response by automx2 from that URL: https://prod-autodetect.outlookmobile.com/detect.

Thanks,

HLFH

**Comment by rseichter** [comment]
I don't remember the versions used for testing during early development. The virtual machines no longer exist after all this time. I asked Microsoft for information about when they used which configuration mechanism in their products, but never received an answer.
