### ISSUE TITLE
Documentation Tests

### ISSUE THREAD

**Issue by Hermann99** [rseichter/automx2#17]
Hi

In section 10 of the documentation, Can you please provide a method to test autodiscovery. 
https://127.0.0.1/autodiscover/autodiscover.xml

Thank you
H

**Comment by rseichter** [comment]
I don't understand your request. The test, and expected output, are [right there](https://rseichter.github.io/automx2/#localtest).

**Comment by Hermann99** [comment]
(https://rseichter.github.io/automx2/#localtest only show the test for autoconfig.
curl 'http://127.0.0.1:4243/mail/config-v1.1.xml?emailaddress=user@example.com'

Autodiscover https://127.0.0.1/autodiscover/autodiscover.xml require a different test since running it gives a method error and require different post variables or format.

# curl https://127.0.0.1/autodiscover/autodiscover.xml
<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>


# curl -X post https://127.0.0.1/autodiscover/autodiscover.xml
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

# curl -X post https://127.0.0.1/autodiscover/autodiscover.xml?emailaddress=user@example.com
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

**Comment by rseichter** [comment]
Ah, I see. The test shown in the documentation is meant to verify that automx2 is running, and returning reasonable data for one of the service endpoints. It is not meant as an exhaustive test suite, like what I used during development. That would require a lot more work for both me and the end user, work which I don't think is worth the effort. I run tests on my end, after all. For end users, it is simpler to rely on their respective MUAs.

**Comment by RobinEd** [comment]
Hi I am running into this as well
XXX.XXX.207.137 - - [02/Apr/2025 19:35:29] "GET /autodiscover/autodiscover.xml HTTP/1.1" 405 -

which when I emulate this using

curl -X GET http://127.0.0.1:4243/autodiscover/autodiscover.xml
or
curl -X GET http://my.server.ext/autodiscover/autodiscover.xml

gives a 
```
<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

However when I test using 
payload.xml
```
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/requestschema/2006">
  <Request>
    <AcceptableResponseSchema>http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a</AcceptableResponseSchema>
    <EMailAddress>jdoe@edgarbv.com</EMailAddress>
  </Request>
</Autodiscover>
```

and then
curl -L -d @payload.xml -H "Content-Type: application/xml" 'http://127.0.0.1:4243/autodiscover/autodiscover.xml'
gives me the expected response:

```
<?xml version="1.0"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a">
    <Account>
      <AccountType>email</AccountType>
      <Action>settings</Action>
      <Protocol>
        <Type>SMTP</Type>
        <Server>mail.myserver.com</Server>
        <Port>587</Port>
        <LoginName>jdoe@myserver.com</LoginName>
        <SSL>off</SSL>
        <Encryption>TLS</Encryption>
      </Protocol>
      <Protocol>
        <Type>IMAP</Type>
        <Server>mail.myserver.com</Server>
        <Port>143</Port>
        <LoginName>jdoe@myserver.com</LoginName>
        <SSL>off</SSL>
        <Encryption>TLS</Encryption>
      </Protocol>
      <Protocol>
        <Type>CalDAV</Type>
        <Server>https://caldav.9e64a1e3b1b04d61a165397b74eeae80.com</Server>
        <Port>443</Port>
        <SSL>on</SSL>
        <DomainRequired>off</DomainRequired>
        <LoginName>jdoe@edgarbv.com</LoginName>
      </Protocol>
      <Protocol>
        <Type>CardDAV</Type>
        <Server>http://carddav.f7cb575b33e047c093b2c853d61ce194.com</Server>
        <SSL>off</SSL>
        <DomainRequired>on</DomainRequired>
      </Protocol>
    </Account>
  </Response>
</Autodiscover>
```

Is this 405 behaviour intended?

Edit: discovered that I was being hit by autodiscover requests from another /24 network at the same time as I was trying with my apple client.

**Comment by rseichter** [comment]
> Is this 405 behaviour intended?

It sure is. Sending a GET request to an endpoint which only processes POST requests is the HTTP equivalent of bringing a knife to a gunfight. 😉

**Comment by RobinEd** [comment]
Thanks. I have been trying to figure out how to get IOS autoconfig to work and the best I have come up with is to use safari to visit https://autoconfig.domain.ext/mobilleconfig/?emailaddress=user@domain.ext then downloading the profile and installing it that way. I was looking at the GET requests thinking that IOS mail app was doing it as the timing was so coincidental!
Is this the only way to get this done or is there a better way that I am missing?

**Comment by rseichter** [comment]
@RobinEd There's a small typo in your URL above, it should be https://hostname.example.com/mobileconfig/?emailaddress=abc%40example.com . You used mobilleconfig with a double "ll". I also recommend using `%40` instead of `@` for proper URL encoding.

That said, opening the URL while using your iOS devices is pretty much the easiest way to go, if you want to avoid the effort of distributing system profiles with Apple's proprietory tooling. The latter allows for the creation of signed profiles, but that's beyond the scope of `automx2` and of what I offer as non-commercial support.

Before I forget: Should you have further issues, please open a new ticket. This one here has been closed for more than a year. Cheers.

**Comment by rseichter** [comment]
@RobinEd Addendum: I have added an explanation to the documentation, hopefully making it easier to understand how mobileconfig can be used.
