### ISSUE TITLE
contrib/sqlite-generate.sh is only good for one domain

### ISSUE THREAD

**Issue by realkinetix** [rseichter/automx2#23]
In trying to get automx2 setup for several domains, I quickly noticed that sqlite-generate.sh wipes each table as it goes to add each entry.

DELETE FROM provider;
DELETE FROM ldapserver;
DELETE FROM server;
DELETE FROM domain;
DELETE FROM server_domain;

As I was only doing this for a very few domains, I changed around the deletes to be specific to the domain and server it rows at hand:

ie:
DELETE FROM domain where name = '${DOMAIN}';

**Comment by rseichter** [comment]
The script works as designed, and it is not the preferred method of seeding automx2 with data anyway. The [documentation](https://rseichter.github.io/automx2/#_sqlite) shows how JSON can be used to populate the database without knowledge of the underlying structure.
