### ISSUE TITLE
k9 (thunderbird) is unable to get settings from /mail/config-v1.1.xml

### ISSUE THREAD

**Issue by bigretromike** [rseichter/automx2#27]
k9 is trying to query automx2 with GET /mail/config-v1.1.xml and end up with code 400, which makes K9 unable to get autoconfiguration. Is there a way to just return .xml to it ?

` [19/Sep/2024:20:32:34 +0200] "GET /mail/config-v1.1.xml HTTP/2.0" 400 39 "-" "okhttp/4.12.0"`

**Comment by bigretromike** [comment]
for now I just redirected it in nginx with:
```
location = /mail/config-v1.1.xml {
   alias /var/www/autoconfig/web/mail/config-v1.1.xml;
 }
```
If there wont be any other solution I will just pull once a time via cron config file with proper url to save it and serve as static file.

**Comment by rseichter** [comment]
You did not provide enough information for me to offer advice. Something in your NGINX configuration may be broken, but details are impossible to know without more data. All I can currently do is point you to the [documentation](https://rseichter.github.io/automx2/#nginx).

**Comment by rseichter** [comment]
Lacking the necessary detailed information to investigate, I will close this issue for the time being. Feel free to reopen it with more data attached. Based on the code 400 ("bad request") alone, it is likely that automx2 is not even being contacted by NGINX.

**Comment by bigretromike** [comment]
@rseichter 
Nginx is configure the way that documentation say to be configured.

Issue is simple, put http://autoconfig.example.com/mail/config-v1.1.xml  in your browser, and you end up with http code 400 and screen with information about missing emailaddress parameter, but k9 aka android thunderbird doesn't use "PUT" command with parameter but it use GET without any parameter. 
And with default configuration it end up with code 400, missing emailaddress parameter. 
Which in my case I solve by ADDing to nginx vhost configuration the alias I post before. 

If this shouldn't be the case, can you point to setting that need to be change so automx2 would not return code 400, missing parameter when "GET" command is sent to the file ?

What more information I need to provide? 

nginx-vhost-config
```
server {
        listen 80;
        listen [::]:80;
        server_name     autoconfig.<redacted>
                        autodiscover.<redacted>;

        root /var/www/autoconfig/web/;

        location = /mail/config-v1.1.xml {
                alias /var/www/autoconfig/web/mail/config-v1.1.xml;
        }

        location / {
            # Forward all traffic to local automx2 service
            proxy_pass http://127.0.0.1:4243/;
            proxy_set_header Host $host;
            # Set config parameter proxy_count=1 to have automx2 process these headers
            proxy_set_header X-Forwarded-Proto http;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
        }
}
```

automx.conf
```
[automx2]
loglevel = DEBUG
db_echo = no
db_uri = sqlite:////srv/www/automx2/db.sqlite
proxy_count = 1

```

**Comment by rseichter** [comment]
> Nginx is configure the way that documentation say to be configured.

@bigretromike It is not. Just compare your configuration with the documented example, line by line. You have added additional options.

> Issue is simple, put http://autoconfig.example.com/mail/config-v1.1.xml in your browser, and you end up with http code 400 and screen with information about missing emailaddress parameter, but k9 aka android thunderbird doesn't use "PUT" command with parameter but it use GET without any parameter.

I don't have access to an Android device using K9, but if that particular software is not sending an email address parameter as [described here](https://rseichter.github.io/automx2/#autoconfig), K9 is not adhering to Mozilla's autoconfig specification. That would be a possible explanation for the return code 400. `emailaddress=foo@example.com` is mandatory. You can test that using a real Thunderbird, or curl. The URL you posted above is incomplete, which is something to discuss with the K9 developers.

**Comment by bigretromike** [comment]
> > Nginx is configure the way that documentation say to be configured.
> 
> @bigretromike It is not. Just compare your configuration with the documented example, line by line. You have added additional options.
> 
Because this way it works with K9, just so anyone looking for this will know.

> > Issue is simple, put http://autoconfig.example.com/mail/config-v1.1.xml in your browser, and you end up with http code 400 and screen with information about missing emailaddress parameter, but k9 aka android thunderbird doesn't use "PUT" command with parameter but it use GET without any parameter.
> 
> I don't have access to an Android device using K9, but if that particular software is not sending an email address parameter as [described here](https://rseichter.github.io/automx2/#autoconfig), K9 is not adhering to Mozilla's autoconfig specification. That would be a possible explanation for the return code 400. `emailaddress=foo@example.com` is mandatory. You can test that using a real Thunderbird, or curl. The URL you posted above is incomplete, which is something to discuss with the K9 developers.

Yes, you are right, looks like Mozilla is not doing their job to stick with their own documentation. I was thinking that this "behaviour" is something build-in automx2 as the documentation and software is Mozilla doing. 

Thanks for confirming that this is not standard behaviour and the workaround need to be on our end not, yours - as its against standard in the documentation. 

If I recall the behaviour did change some time ago in K9 and I wasn't sure if its badly automx2 configuration or K9 issue, now i know. 
Thanks

**Comment by rseichter** [comment]
> Because this way it works with K9, just so anyone looking for this will know.

Maybe I misunderstand. What do you mean by "it works"? At a glance, your modified configuration seems to circumvent/disable automx2 and redirect to a static file instead. What good does serving a static config file do in this context? The whole point of automx2 is to serve dynamic configuration data, so I am not sure in what sense "it works"?

> Yes, you are right, looks like Mozilla is not doing their job to stick with their own documentation. (...) Thanks for confirming that this is not standard behaviour and the workaround need to be on our end not, yours

If by workaround you mean that K9 needs to provide the parameters required by the protocol, then yes. 😉

**Comment by bigretromike** [comment]
> > Because this way it works with K9, just so anyone looking for this will know.
> 
> Maybe I misunderstand. What do you mean by "it works"? At a glance, your modified configuration seems to circumvent/disable automx2 and redirect to a static file instead. What good does serving a static config file do in this context? The whole point of automx2 is to serve dynamic configuration data, so I am not sure in what sense "it works"?
I had to bypass automx2 because it doesn't serve config-v1.1.xml under /mail/ for "GET" requests without parameter, I just curl via cron config-v1.1.xml with parameter, save that as static file and serve it. I have few people that use K9 and its "temporary" fix for the issue. For now it works in my case. Probably not the best way to overcome this but... 

 Yes, you are right, looks like Mozilla is not doing their job to stick with their own documentation. (...) Thanks for confirming that this is not standard behaviour and the workaround need to be on our end not, yours
> 
> If by workaround you mean that K9 needs to provide the parameters required by the protocol, then yes. 😉

Yes, that would be the best.  I will make issue for that
