### ISSUE TITLE
unknown collation in mysql schema

### ISSUE THREAD

**Issue by xinomilo** [rseichter/automx2#28]
hey,
trying to install automx2 for test, and wanted to remove sample data, so i used [mysql-schema.sql](https://github.com/rseichter/automx2/blob/master/contrib/mysql-schema.sql) to delete and recreate tables , but : 

$ mysql automx2 < mysql-schema.sql 
ERROR 1273 (HY000) at line 25: Unknown collation: 'utf8mb4_0900_ai_ci'

changing collation to utf8mb4_general_ci  (like : https://github.com/rseichter/automx2/blob/master/docs/dbconfig.adoc?plain=1#L98 ) works fine.

debian 12, python 3.11.2 + pymysql in venv.

thanks,

**Comment by rseichter** [comment]
Thanks for the information. The recommended way to populate a MySQL database is documented [here](https://rseichter.github.io/automx2/#_mysql).

The SQL dump you referenced is based on the outdated MySQL version 10.x and therefore not expected to work with more modern versions. Perhaps I should remove this particular dump file altogether, it does not really serve a practical purpose anymore.

**Comment by xinomilo** [comment]
yes, populate mysql works as documented, just wanted to remove sample data afterwards. 
hadnt seen the DELETE command from docs when i reported the issue, it also works fine btw.
(DELETE might be limited in some web server configurations, one has to manually allow it first.)

i think file can be removed. if needed, sql schema can be created after documented mysql population, using 
eg.  : `mysqldump automx2 > mysql-schema.sql `

thanks,
