### ISSUE TITLE
how to do wildcard domains

### ISSUE THREAD

**Issue by sep76** [rseichter/automx2#5]
Hello 

I have traditionally written my own autodiscovery.xml manually. But your project seems very convenient, so I wanted to give it a try. 

have a very simple setup with a single provider, single imap and singe smtp for multiple domains. 
it works when i enter a specific domain in domains table,  But i do not understand how to map all domains ever queried on the server to a single provider/server set. basically a wildcard using %EMAILDOMAIN%  as the domain part.

**Comment by rseichter** [comment]
Are you asking about default responses for undefined domains? As I mentioned a few days ago on the [automx2 mailing list](https://mail.sys4.de/pipermail/automx-users/2022-January/000308.html), this is not currently supported.

**Comment by sep76** [comment]
was exactly what i was asking about. and I see the answer there.  you can close the issue, or keep it as a wishlist bug if you want.

**Comment by rseichter** [comment]
I'll close this issue for the time being, because I won't add this feature in the foreseeable future. It might be reopened if necessary.
